services:
  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy
    command: serve --config /etc/ntfy/server.yml
    ports:
      - "8098:8098"
    volumes:
      - ./data/server.yml:/etc/ntfy/server.yml:ro
      - ./data:/var/lib/ntfy:rw
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://127.0.0.1:8098/v1/health"]
      interval: 30s
      timeout: 5s
      retries: 3
